# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c758037d6b4e9f42babfe60b7ed9597159e11fbda9ae171a39ddc8a3a3c859796201ee2fdd6c1b85797309dc13c2f4777045a8d7cea44ae16f31886fb8d9621d
  nutritionix_app_id: <%= ENV["NUTRITIONIX_APP_ID"] %>
  nutritionix_app_key: <%= ENV["NUTRITIONIX_APP_KEY"] %>

test:
  secret_key_base: c758037d6b4e9f42babfe60b7ed9597159e11fbda9ae171a39ddc8a3a3c859796201ee2fdd6c1b85797309dc13c2f4777045a8d7cea44ae16f31886fb8d9621d
  nutritionix_app_id: <%= ENV["NUTRITIONIX_APP_ID"] %>
  nutritionix_app_key: <%= ENV["NUTRITIONIX_APP_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c758037d6b4e9f42babfe60b7ed9597159e11fbda9ae171a39ddc8a3a3c859796201ee2fdd6c1b85797309dc13c2f4777045a8d7cea44ae16f31886fb8d9621d
  nutritionix_app_id: <%= ENV["NUTRITIONIX_APP_ID"] %>
  nutritionix_app_key: <%= ENV["NUTRITIONIX_APP_KEY"] %>
